version: "3"

services:

  # MySQL

  mysql:
    image: mysql:5.7
    container_name: python_mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    ports:
      - 3306:3306
    environment:
      #MYSQL_DATABASE: lesson_14
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/1.sql:rw
